name: Build Release Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  Build-Release-Android-APK:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'android')"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: "setup-node@v3"
        uses: actions/setup-node@v3
        with:
          node-version: 18											  
      - name: "Install Node Dependencies"
        run: |
          npm i						
      - name: "Build and Release"
        run: |
          cd android	 
          chmod a+x gradlew
          ./gradlew build
          ./gradlew assembleRelease
          ./gradlew app:bundleRelease
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.STORE_PASSWORD }}

      - name: "upload apk to App Center"
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: "jeyapriya@vthink.co.in/React-App"
          token: ${{secrets.APP_CENTER_TOKEN}}
          file: ./android/app/build/outputs/apk/release/app-release.apk
          group: "tester" 
          notifyTesters: "true"







